language: python
python:
  - "3.6"
install:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - "pip install -r requirements.txt"
  - sudo mv nltk_data /usr/share/nltk_data

script:
  - python -m pytest -v test/
